#%RAML 1.0
title: Sample API

/home:
  get:
    responses:
      200:
        body:
          application/html:
/generate:
  get:
    queryParameters:
      project:
        required: true
    responses:
      200:
        body:
          application/octet-stream: